### PR TITLE
ci: erase nRF9160 at end of tests

### PR DESCRIPTION
**Pull request by szczys**
Enable nRF9160dk CI testing with an erase step as the final (required) step of the workflow. This ensures that after a test a dev board will not continue to be connected to the cellular network, accruing data usage charges.

### CODE REVIEW

**Comment by sam-golioth** [comment]
Would it be straightforward to also erase the other boards?

**Comment by sam-golioth** [comment]
Let's investigate why there are so many failures on the 9160 twister tests.

**Comment by sam-golioth** [comment]
> Would it be straightforward to also erase the other boards?

@szczys latest changes look good, but still waiting on this

**Comment by szczys** [comment]
> Let's investigate why there are so many failures on the 9160 twister tests.

**Comment by szczys** [comment]
> > Would it be straightforward to also erase the other boards?
> 
> @szczys latest changes look good, but still waiting on this

I've added erase commands for the rest of the boards and CI has passed.

**Comment by szczys** [comment]
Oops, clicked close by mistake

**Review by sam-golioth — APPROVED** [review]

**Pull request merged**
