### PR TITLE
zephyr: add test for the logging sample

### PR DESCRIPTION
**Pull request by szczys**
Check that each type of log massage is received, verifying both message text and log level.

### CODE REVIEW

**Comment by szczys** [comment]
@sam-golioth I don't understand why the esp32_devkitc_wrover test is getting skipped in this PR. Any thoughts?

https://github.com/golioth/golioth-firmware-sdk/actions/runs/7198154736/job/19607342471

**Review by sam-golioth — APPROVED** [review]
Great work @szczys! Let's file a ticket for the failures. Regarding those - are they consistent or intermittent?

**Comment by szczys** [comment]
> Great work @szczys! Let's file a ticket for the failures. Regarding those - are they consistent or intermittent?

It is consistent that logs will not be found, but the logs that get dropped change between runs and between devices. I have seen some devices successfully pass the test, but never all devices during a single test.

**Comment by szczys** [comment]
The behavior we are encountering is tracked in this issue: https://github.com/golioth/firmware-issue-tracker/issues/218

**Pull request merged**
